// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// optimal_topic_core
arma::mat optimal_topic_core(const Rcpp::List& lda_models, const arma::sp_mat& weighted_dfm, double q, const Rcpp::CharacterVector& docs, int n_docs, int n_features);
RcppExport SEXP _OpTop_optimal_topic_core(SEXP lda_modelsSEXP, SEXP weighted_dfmSEXP, SEXP qSEXP, SEXP docsSEXP, SEXP n_docsSEXP, SEXP n_featuresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type lda_models(lda_modelsSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type weighted_dfm(weighted_dfmSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type docs(docsSEXP);
    Rcpp::traits::input_parameter< int >::type n_docs(n_docsSEXP);
    Rcpp::traits::input_parameter< int >::type n_features(n_featuresSEXP);
    rcpp_result_gen = Rcpp::wrap(optimal_topic_core(lda_models, weighted_dfm, q, docs, n_docs, n_features));
    return rcpp_result_gen;
END_RCPP
}
// topic_match_core
Rcpp::List topic_match_core(const Rcpp::List& lda_models, std::size_t best_pos, std::size_t optimal_k, bool var_correction);
RcppExport SEXP _OpTop_topic_match_core(SEXP lda_modelsSEXP, SEXP best_posSEXP, SEXP optimal_kSEXP, SEXP var_correctionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type lda_models(lda_modelsSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type best_pos(best_posSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type optimal_k(optimal_kSEXP);
    Rcpp::traits::input_parameter< bool >::type var_correction(var_correctionSEXP);
    rcpp_result_gen = Rcpp::wrap(topic_match_core(lda_models, best_pos, optimal_k, var_correction));
    return rcpp_result_gen;
END_RCPP
}
// normalize_columns
arma::mat normalize_columns(const arma::mat& x);
RcppExport SEXP _OpTop_normalize_columns(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(normalize_columns(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_OpTop_optimal_topic_core", (DL_FUNC) &_OpTop_optimal_topic_core, 6},
    {"_OpTop_topic_match_core", (DL_FUNC) &_OpTop_topic_match_core, 4},
    {"_OpTop_normalize_columns", (DL_FUNC) &_OpTop_normalize_columns, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_OpTop(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
