// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// optop_boot_null_core
Rcpp::NumericVector optop_boot_null_core(const Rcpp::NumericVector& bin_probs, const Rcpp::IntegerVector& bin_counts, const Rcpp::NumericVector& doc_lengths, int n_boot, double seed, int n_threads, double doc_offset);
RcppExport SEXP _OpTop_optop_boot_null_core(SEXP bin_probsSEXP, SEXP bin_countsSEXP, SEXP doc_lengthsSEXP, SEXP n_bootSEXP, SEXP seedSEXP, SEXP n_threadsSEXP, SEXP doc_offsetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type bin_probs(bin_probsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type bin_counts(bin_countsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type doc_lengths(doc_lengthsSEXP);
    Rcpp::traits::input_parameter< int >::type n_boot(n_bootSEXP);
    Rcpp::traits::input_parameter< double >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< double >::type doc_offset(doc_offsetSEXP);
    rcpp_result_gen = Rcpp::wrap(optop_boot_null_core(bin_probs, bin_counts, doc_lengths, n_boot, seed, n_threads, doc_offset));
    return rcpp_result_gen;
END_RCPP
}
// optop_openmp_available
bool optop_openmp_available();
RcppExport SEXP _OpTop_optop_openmp_available() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(optop_openmp_available());
    return rcpp_result_gen;
END_RCPP
}
// optop_index_word_core
Rcpp::NumericMatrix optop_index_word_core(const arma::mat& theta, const arma::mat& phi_cols, const Rcpp::IntegerVector& N_p, const Rcpp::IntegerVector& N_i, const Rcpp::NumericVector& N_x, int w_start, int w_len, const Rcpp::NumericVector& L, const Rcpp::NumericVector& pi_w, double eps, bool do_model, bool do_null, bool do_se, bool do_chisq, bool do_dev, int n_threads);
RcppExport SEXP _OpTop_optop_index_word_core(SEXP thetaSEXP, SEXP phi_colsSEXP, SEXP N_pSEXP, SEXP N_iSEXP, SEXP N_xSEXP, SEXP w_startSEXP, SEXP w_lenSEXP, SEXP LSEXP, SEXP pi_wSEXP, SEXP epsSEXP, SEXP do_modelSEXP, SEXP do_nullSEXP, SEXP do_seSEXP, SEXP do_chisqSEXP, SEXP do_devSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type phi_cols(phi_colsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type N_p(N_pSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type N_i(N_iSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type N_x(N_xSEXP);
    Rcpp::traits::input_parameter< int >::type w_start(w_startSEXP);
    Rcpp::traits::input_parameter< int >::type w_len(w_lenSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type pi_w(pi_wSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< bool >::type do_model(do_modelSEXP);
    Rcpp::traits::input_parameter< bool >::type do_null(do_nullSEXP);
    Rcpp::traits::input_parameter< bool >::type do_se(do_seSEXP);
    Rcpp::traits::input_parameter< bool >::type do_chisq(do_chisqSEXP);
    Rcpp::traits::input_parameter< bool >::type do_dev(do_devSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(optop_index_word_core(theta, phi_cols, N_p, N_i, N_x, w_start, w_len, L, pi_w, eps, do_model, do_null, do_se, do_chisq, do_dev, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// optop_index_doc_core
Rcpp::NumericMatrix optop_index_doc_core(const arma::mat& theta, const arma::mat& phi, const Rcpp::IntegerVector& Nt_p, const Rcpp::IntegerVector& Nt_i, const Rcpp::NumericVector& Nt_x, const Rcpp::NumericVector& nr_off, const Rcpp::IntegerVector& nr_words, const Rcpp::NumericVector& L, const Rcpp::NumericVector& pi_row, const Rcpp::LogicalVector& chisq_min_ok, double eps, bool do_model, bool do_null, bool do_se, bool do_chisq, bool do_dev, int n_threads);
RcppExport SEXP _OpTop_optop_index_doc_core(SEXP thetaSEXP, SEXP phiSEXP, SEXP Nt_pSEXP, SEXP Nt_iSEXP, SEXP Nt_xSEXP, SEXP nr_offSEXP, SEXP nr_wordsSEXP, SEXP LSEXP, SEXP pi_rowSEXP, SEXP chisq_min_okSEXP, SEXP epsSEXP, SEXP do_modelSEXP, SEXP do_nullSEXP, SEXP do_seSEXP, SEXP do_chisqSEXP, SEXP do_devSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type Nt_p(Nt_pSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type Nt_i(Nt_iSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type Nt_x(Nt_xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type nr_off(nr_offSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type nr_words(nr_wordsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type pi_row(pi_rowSEXP);
    Rcpp::traits::input_parameter< const Rcpp::LogicalVector& >::type chisq_min_ok(chisq_min_okSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< bool >::type do_model(do_modelSEXP);
    Rcpp::traits::input_parameter< bool >::type do_null(do_nullSEXP);
    Rcpp::traits::input_parameter< bool >::type do_se(do_seSEXP);
    Rcpp::traits::input_parameter< bool >::type do_chisq(do_chisqSEXP);
    Rcpp::traits::input_parameter< bool >::type do_dev(do_devSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(optop_index_doc_core(theta, phi, Nt_p, Nt_i, Nt_x, nr_off, nr_words, L, pi_row, chisq_min_ok, eps, do_model, do_null, do_se, do_chisq, do_dev, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// optimal_topic_core
Rcpp::List optimal_topic_core(const arma::mat& theta, const arma::mat& phi, const Rcpp::IntegerVector& dfm_p, const Rcpp::IntegerVector& dfm_i, const Rcpp::NumericVector& dfm_x, int n_terms_in, double q, const arma::uvec& doc_map, bool return_envelope, int n_threads);
RcppExport SEXP _OpTop_optimal_topic_core(SEXP thetaSEXP, SEXP phiSEXP, SEXP dfm_pSEXP, SEXP dfm_iSEXP, SEXP dfm_xSEXP, SEXP n_terms_inSEXP, SEXP qSEXP, SEXP doc_mapSEXP, SEXP return_envelopeSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type dfm_p(dfm_pSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type dfm_i(dfm_iSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type dfm_x(dfm_xSEXP);
    Rcpp::traits::input_parameter< int >::type n_terms_in(n_terms_inSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type doc_map(doc_mapSEXP);
    Rcpp::traits::input_parameter< bool >::type return_envelope(return_envelopeSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(optimal_topic_core(theta, phi, dfm_p, dfm_i, dfm_x, n_terms_in, q, doc_map, return_envelope, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// optop_partition_candidates_core
Rcpp::IntegerVector optop_partition_candidates_core(const Rcpp::NumericVector& pi_sorted, const Rcpp::NumericVector& tau, int n_threads);
RcppExport SEXP _OpTop_optop_partition_candidates_core(SEXP pi_sortedSEXP, SEXP tauSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type pi_sorted(pi_sortedSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(optop_partition_candidates_core(pi_sorted, tau, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// optop_partition_pass_core
void optop_partition_pass_core(const arma::mat& theta, const arma::mat& phi, const Rcpp::IntegerVector& order, const Rcpp::NumericVector& cand_off, Rcpp::RawVector keep, const Rcpp::NumericVector& tau, double doc_offset, int n_threads);
RcppExport SEXP _OpTop_optop_partition_pass_core(SEXP thetaSEXP, SEXP phiSEXP, SEXP orderSEXP, SEXP cand_offSEXP, SEXP keepSEXP, SEXP tauSEXP, SEXP doc_offsetSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type order(orderSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type cand_off(cand_offSEXP);
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type keep(keepSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type doc_offset(doc_offsetSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    optop_partition_pass_core(theta, phi, order, cand_off, keep, tau, doc_offset, n_threads);
    return R_NilValue;
END_RCPP
}
// optop_partition_compact_core
Rcpp::List optop_partition_compact_core(const Rcpp::NumericVector& cand_off, const Rcpp::RawVector& keep, const Rcpp::IntegerVector& order, int n_threads);
RcppExport SEXP _OpTop_optop_partition_compact_core(SEXP cand_offSEXP, SEXP keepSEXP, SEXP orderSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type cand_off(cand_offSEXP);
    Rcpp::traits::input_parameter< const Rcpp::RawVector& >::type keep(keepSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type order(orderSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(optop_partition_compact_core(cand_off, keep, order, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// optop_partition_sums_core
Rcpp::NumericVector optop_partition_sums_core(const arma::mat& theta, const arma::mat& phi, const Rcpp::NumericVector& nr_off, const Rcpp::IntegerVector& nr_words, double doc_offset, int n_threads);
RcppExport SEXP _OpTop_optop_partition_sums_core(SEXP thetaSEXP, SEXP phiSEXP, SEXP nr_offSEXP, SEXP nr_wordsSEXP, SEXP doc_offsetSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type nr_off(nr_offSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type nr_words(nr_wordsSEXP);
    Rcpp::traits::input_parameter< double >::type doc_offset(doc_offsetSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(optop_partition_sums_core(theta, phi, nr_off, nr_words, doc_offset, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// optop_partition_pisum_core
Rcpp::NumericVector optop_partition_pisum_core(const Rcpp::NumericVector& nr_off, const Rcpp::IntegerVector& nr_words, const Rcpp::NumericVector& pi_glob, int n_threads);
RcppExport SEXP _OpTop_optop_partition_pisum_core(SEXP nr_offSEXP, SEXP nr_wordsSEXP, SEXP pi_globSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type nr_off(nr_offSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type nr_words(nr_wordsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type pi_glob(pi_globSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(optop_partition_pisum_core(nr_off, nr_words, pi_glob, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// optop_partition_obsmass_core
Rcpp::NumericVector optop_partition_obsmass_core(const Rcpp::IntegerVector& Nt_p, const Rcpp::IntegerVector& Nt_i, const Rcpp::NumericVector& Nt_x, const Rcpp::NumericVector& nr_off, const Rcpp::IntegerVector& nr_words, double doc_offset, int n_threads);
RcppExport SEXP _OpTop_optop_partition_obsmass_core(SEXP Nt_pSEXP, SEXP Nt_iSEXP, SEXP Nt_xSEXP, SEXP nr_offSEXP, SEXP nr_wordsSEXP, SEXP doc_offsetSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type Nt_p(Nt_pSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type Nt_i(Nt_iSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type Nt_x(Nt_xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type nr_off(nr_offSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type nr_words(nr_wordsSEXP);
    Rcpp::traits::input_parameter< double >::type doc_offset(doc_offsetSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(optop_partition_obsmass_core(Nt_p, Nt_i, Nt_x, nr_off, nr_words, doc_offset, n_threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_OpTop_optop_boot_null_core", (DL_FUNC) &_OpTop_optop_boot_null_core, 7},
    {"_OpTop_optop_openmp_available", (DL_FUNC) &_OpTop_optop_openmp_available, 0},
    {"_OpTop_optop_index_word_core", (DL_FUNC) &_OpTop_optop_index_word_core, 16},
    {"_OpTop_optop_index_doc_core", (DL_FUNC) &_OpTop_optop_index_doc_core, 17},
    {"_OpTop_optimal_topic_core", (DL_FUNC) &_OpTop_optimal_topic_core, 10},
    {"_OpTop_optop_partition_candidates_core", (DL_FUNC) &_OpTop_optop_partition_candidates_core, 3},
    {"_OpTop_optop_partition_pass_core", (DL_FUNC) &_OpTop_optop_partition_pass_core, 8},
    {"_OpTop_optop_partition_compact_core", (DL_FUNC) &_OpTop_optop_partition_compact_core, 4},
    {"_OpTop_optop_partition_sums_core", (DL_FUNC) &_OpTop_optop_partition_sums_core, 6},
    {"_OpTop_optop_partition_pisum_core", (DL_FUNC) &_OpTop_optop_partition_pisum_core, 4},
    {"_OpTop_optop_partition_obsmass_core", (DL_FUNC) &_OpTop_optop_partition_obsmass_core, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_OpTop(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
