# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
optop_boot_null_core <- function(bin_probs, bin_counts, doc_lengths, n_boot, seed, n_threads) {
    .Call(`_OpTop_optop_boot_null_core`, bin_probs, bin_counts, doc_lengths, n_boot, seed, n_threads)
}

#' @keywords internal
optop_openmp_available <- function() {
    .Call(`_OpTop_optop_openmp_available`)
}

#' @keywords internal
optimal_topic_core <- function(theta, phi, dfm_t, q, doc_map, return_envelope, n_threads) {
    .Call(`_OpTop_optimal_topic_core`, theta, phi, dfm_t, q, doc_map, return_envelope, n_threads)
}

#' @keywords internal
optimal_topic_core_legacy <- function(lda_models, weighted_dfm, q, doc_map) {
    .Call(`_OpTop_optimal_topic_core_legacy`, lda_models, weighted_dfm, q, doc_map)
}

#' @keywords internal
topic_match_core <- function(lda_models, best_pos, optimal_k, var_correction) {
    .Call(`_OpTop_topic_match_core`, lda_models, best_pos, optimal_k, var_correction)
}

#' @keywords internal
normalize_columns <- function(x) {
    .Call(`_OpTop_normalize_columns`, x)
}

