# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
optop_boot_null_core <- function(bin_probs, bin_counts, doc_lengths, n_boot, seed, n_threads) {
    .Call(`_OpTop_optop_boot_null_core`, bin_probs, bin_counts, doc_lengths, n_boot, seed, n_threads)
}

#' @keywords internal
optop_openmp_available <- function() {
    .Call(`_OpTop_optop_openmp_available`)
}

#' @keywords internal
optop_index_word_core <- function(theta, phi_cols, N_p, N_i, N_x, w_start, w_len, L, pi_w, eps, do_model, do_null, do_se, do_chisq, do_dev, n_threads) {
    .Call(`_OpTop_optop_index_word_core`, theta, phi_cols, N_p, N_i, N_x, w_start, w_len, L, pi_w, eps, do_model, do_null, do_se, do_chisq, do_dev, n_threads)
}

#' @keywords internal
optop_index_doc_core <- function(theta, phi, Nt_p, Nt_i, Nt_x, nr_off, nr_words, L, pi_row, chisq_min_ok, eps, do_model, do_null, do_se, do_chisq, do_dev, n_threads) {
    .Call(`_OpTop_optop_index_doc_core`, theta, phi, Nt_p, Nt_i, Nt_x, nr_off, nr_words, L, pi_row, chisq_min_ok, eps, do_model, do_null, do_se, do_chisq, do_dev, n_threads)
}

#' @keywords internal
optimal_topic_core <- function(theta, phi, dfm_p, dfm_i, dfm_x, n_terms_in, q, doc_map, return_envelope, n_threads) {
    .Call(`_OpTop_optimal_topic_core`, theta, phi, dfm_p, dfm_i, dfm_x, n_terms_in, q, doc_map, return_envelope, n_threads)
}

#' @keywords internal
optimal_topic_core_legacy <- function(lda_models, weighted_dfm, q, doc_map) {
    .Call(`_OpTop_optimal_topic_core_legacy`, lda_models, weighted_dfm, q, doc_map)
}

#' @keywords internal
optop_partition_candidates_core <- function(pi_sorted, tau, n_threads) {
    .Call(`_OpTop_optop_partition_candidates_core`, pi_sorted, tau, n_threads)
}

#' @keywords internal
optop_partition_pass_core <- function(theta, phi, order, cand_off, keep, tau, n_threads) {
    invisible(.Call(`_OpTop_optop_partition_pass_core`, theta, phi, order, cand_off, keep, tau, n_threads))
}

#' @keywords internal
optop_partition_compact_core <- function(cand_off, keep, order, n_threads) {
    .Call(`_OpTop_optop_partition_compact_core`, cand_off, keep, order, n_threads)
}

#' @keywords internal
optop_partition_sums_core <- function(theta, phi, nr_off, nr_words, n_threads) {
    .Call(`_OpTop_optop_partition_sums_core`, theta, phi, nr_off, nr_words, n_threads)
}

#' @keywords internal
optop_partition_pisum_core <- function(nr_off, nr_words, pi_glob, n_threads) {
    .Call(`_OpTop_optop_partition_pisum_core`, nr_off, nr_words, pi_glob, n_threads)
}

#' @keywords internal
optop_partition_obsmass_core <- function(Nt_p, Nt_i, Nt_x, nr_off, nr_words, n_threads) {
    .Call(`_OpTop_optop_partition_obsmass_core`, Nt_p, Nt_i, Nt_x, nr_off, nr_words, n_threads)
}

#' @keywords internal
topic_match_core <- function(lda_models, best_pos, optimal_k, var_correction) {
    .Call(`_OpTop_topic_match_core`, lda_models, best_pos, optimal_k, var_correction)
}

#' @keywords internal
normalize_columns <- function(x) {
    .Call(`_OpTop_normalize_columns`, x)
}

